package com.rupiksha.backend.domain;

public enum WalletTransactionContext {
    ADMIN_CREDIT,
    ADMIN_DEBIT,
    FUND_REQUEST_CREATED,
    FUND_REQUEST_APPROVED,
    FUND_REQUEST_REJECTED,
    AEPS_CASH_WITHDRAWAL,
    AEPS_BALANCE_INQUIRY,
    AEPS_MINI_STATEMENT,
    AEPS_AADHAAR_PAY,
    AEPS_REFUND,
    AEPS_DEPOSIT,
    BBPS_PAYMENT,
    RECHARGE,
    DMT_TRANSFER,
    PAYOUT,
    PAYOUT_REFUND,
    COMMISSION,
    TAX_DEDUCTION,
    LOCK_BALANCE,
    RELEASE_LOCK,
    MANUAL_ADJUSTMENT,
    SYSTEM_ADJUSTMENT,
    STATUS_CHANGE,
    REVERSAL,
    PLAN_UPGRADE
}
