version: "3.9"
services:
  postgres:
    image: postgres:16
    container_name: rupiksha-postgres
    environment:
      POSTGRES_DB: rupiksha
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
    ports:
      - "5432:5432"
    volumes:
      - pg_data:/var/lib/postgresql/data

  redis:
    image: redis:7-alpine
    container_name: rupiksha-redis
    ports:
      - "6379:6379"

volumes:
  pg_data:
