// ── Operator prefix → { operator, circle }
export const PREFIX_DB = {
    // AIRTEL
    "9810": { op: "Airtel", circle: "Delhi" }, "9811": { op: "Airtel", circle: "Delhi" },
    "9868": { op: "Airtel", circle: "Delhi" }, "9871": { op: "Airtel", circle: "Delhi" },
    "9958": { op: "Airtel", circle: "Delhi" }, "9999": { op: "Airtel", circle: "Delhi" },
    "9820": { op: "Airtel", circle: "Mumbai" }, "9821": { op: "Airtel", circle: "Mumbai" },
    "9769": { op: "Airtel", circle: "Mumbai" }, "9987": { op: "Airtel", circle: "Mumbai" },
    "9412": { op: "Airtel", circle: "UP West" }, "9458": { op: "Airtel", circle: "UP East" },
    "9415": { op: "Airtel", circle: "UP East" }, "9936": { op: "Airtel", circle: "UP East" },
    "9839": { op: "Airtel", circle: "UP East" }, "9335": { op: "Airtel", circle: "UP East" },
    "9934": { op: "Airtel", circle: "Bihar" }, "9304": { op: "Airtel", circle: "Bihar" },
    "9693": { op: "Airtel", circle: "Bihar" }, "9771": { op: "Airtel", circle: "Bihar" },
    "9316": { op: "Airtel", circle: "Rajasthan" }, "9414": { op: "Airtel", circle: "Rajasthan" },
    "9828": { op: "Airtel", circle: "Rajasthan" }, "9829": { op: "Airtel", circle: "Rajasthan" },
    "9560": { op: "Airtel", circle: "Delhi" }, "9599": { op: "Airtel", circle: "Delhi" },
    "9711": { op: "Airtel", circle: "Delhi" }, "9718": { op: "Airtel", circle: "Delhi" },
    "8527": { op: "Airtel", circle: "Delhi" }, "8800": { op: "Airtel", circle: "Delhi" },
    "7011": { op: "Airtel", circle: "Delhi" }, "7982": { op: "Airtel", circle: "Delhi" },
    "9205": { op: "Airtel", circle: "Haryana" }, "9896": { op: "Airtel", circle: "Haryana" },
    "9416": { op: "Airtel", circle: "Haryana" }, "9466": { op: "Airtel", circle: "Haryana" },
    "9419": { op: "Airtel", circle: "J&K" }, "9797": { op: "Airtel", circle: "J&K" },
    "9906": { op: "Airtel", circle: "J&K" }, "9419": { op: "Airtel", circle: "J&K" },
    "9431": { op: "Airtel", circle: "Jharkhand" }, "8986": { op: "Airtel", circle: "Jharkhand" },
    "9471": { op: "Airtel", circle: "Jharkhand" }, "8340": { op: "Airtel", circle: "Bihar" },
    "9480": { op: "Airtel", circle: "Karnataka" }, "9481": { op: "Airtel", circle: "Karnataka" },
    "9900": { op: "Airtel", circle: "Karnataka" }, "9901": { op: "Airtel", circle: "Karnataka" },
    "9846": { op: "Airtel", circle: "Kerala" }, "9847": { op: "Airtel", circle: "Kerala" },
    "9605": { op: "Airtel", circle: "Kerala" }, "9526": { op: "Airtel", circle: "Kerala" },
    "9827": { op: "Airtel", circle: "MP" }, "9893": { op: "Airtel", circle: "MP" },
    "9753": { op: "Airtel", circle: "MP" }, "9826": { op: "Airtel", circle: "MP" },
    "9373": { op: "Airtel", circle: "Maharashtra" }, "9823": { op: "Airtel", circle: "Maharashtra" },
    "9860": { op: "Airtel", circle: "Maharashtra" }, "9561": { op: "Airtel", circle: "Maharashtra" },
    "9433": { op: "Airtel", circle: "West Bengal" }, "9434": { op: "Airtel", circle: "West Bengal" },
    "9832": { op: "Airtel", circle: "West Bengal" }, "7595": { op: "Airtel", circle: "West Bengal" },
    "9444": { op: "Airtel", circle: "Tamil Nadu" }, "9445": { op: "Airtel", circle: "Tamil Nadu" },
    "9841": { op: "Airtel", circle: "Tamil Nadu" }, "9791": { op: "Airtel", circle: "Tamil Nadu" },
    "9177": { op: "Airtel", circle: "Andhra Pradesh" }, "9849": { op: "Airtel", circle: "Andhra Pradesh" },
    "9866": { op: "Airtel", circle: "Andhra Pradesh" }, "9963": { op: "Airtel", circle: "Andhra Pradesh" },
    // JIO
    "6260": { op: "Jio", circle: "MP" }, "6261": { op: "Jio", circle: "MP" },
    "7000": { op: "Jio", circle: "MP" }, "7001": { op: "Jio", circle: "UP East" },
    "7002": { op: "Jio", circle: "Rajasthan" }, "7003": { op: "Jio", circle: "Delhi" },
    "7004": { op: "Jio", circle: "Gujarat" }, "7005": { op: "Jio", circle: "Maharashtra" },
    "7006": { op: "Jio", circle: "UP West" }, "7007": { op: "Jio", circle: "Bihar" },
    "7008": { op: "Jio", circle: "Odisha" }, "7009": { op: "Jio", circle: "Haryana" },
    "7568": { op: "Jio", circle: "Rajasthan" }, "8269": { op: "Jio", circle: "MP" },
    "8349": { op: "Jio", circle: "MP" }, "9109": { op: "Jio", circle: "MP" },
    "6261": { op: "Jio", circle: "MP" }, "6262": { op: "Jio", circle: "MP" },
    "6263": { op: "Jio", circle: "UP East" }, "6264": { op: "Jio", circle: "Bihar" },
    "6265": { op: "Jio", circle: "Bihar" }, "6266": { op: "Jio", circle: "UP West" },
    "6267": { op: "Jio", circle: "Maharashtra" }, "6268": { op: "Jio", circle: "Gujarat" },
    "6269": { op: "Jio", circle: "Rajasthan" }, "9175": { op: "Jio", circle: "Maharashtra" },
    "9326": { op: "Jio", circle: "Maharashtra" }, "9619": { op: "Jio", circle: "Maharashtra" },
    "7350": { op: "Jio", circle: "UP East" }, "7838": { op: "Jio", circle: "Delhi" },
    "8299": { op: "Jio", circle: "UP East" }, "8874": { op: "Jio", circle: "UP East" },
    "9076": { op: "Jio", circle: "Maharashtra" }, "9307": { op: "Jio", circle: "Bihar" },
    "9508": { op: "Jio", circle: "Bihar" }, "9155": { op: "Jio", circle: "Andhra Pradesh" },
    "9059": { op: "Jio", circle: "Andhra Pradesh" }, "9010": { op: "Jio", circle: "Andhra Pradesh" },
    "9182": { op: "Jio", circle: "Andhra Pradesh" }, "9247": { op: "Jio", circle: "Andhra Pradesh" },
    // Vi (Vodafone Idea)
    "9320": { op: "Vi", circle: "Mumbai" }, "9321": { op: "Vi", circle: "Mumbai" },
    "9322": { op: "Vi", circle: "Mumbai" }, "9323": { op: "Vi", circle: "Mumbai" },
    "9324": { op: "Vi", circle: "Mumbai" }, "9325": { op: "Vi", circle: "Mumbai" },
    "9768": { op: "Vi", circle: "Delhi" }, "9773": { op: "Vi", circle: "Delhi" },
    "9990": { op: "Vi", circle: "Delhi" }, "9311": { op: "Vi", circle: "Delhi" },
    "9312": { op: "Vi", circle: "Delhi" }, "9313": { op: "Vi", circle: "Delhi" },
    "9773": { op: "Vi", circle: "Delhi" }, "9899": { op: "Vi", circle: "Delhi" },
    "9829": { op: "Vi", circle: "Rajasthan" }, "9460": { op: "Vi", circle: "Rajasthan" },
    "9461": { op: "Vi", circle: "Rajasthan" }, "9462": { op: "Vi", circle: "Rajasthan" },
    "9425": { op: "Vi", circle: "MP" }, "9926": { op: "Vi", circle: "MP" },
    "9827": { op: "Vi", circle: "MP" }, "9977": { op: "Vi", circle: "MP" },
    "9924": { op: "Vi", circle: "Gujarat" }, "9925": { op: "Vi", circle: "Gujarat" },
    "9978": { op: "Vi", circle: "Gujarat" }, "8980": { op: "Vi", circle: "Gujarat" },
    "9391": { op: "Vi", circle: "Andhra Pradesh" }, "9440": { op: "Vi", circle: "Andhra Pradesh" },
    "9441": { op: "Vi", circle: "Andhra Pradesh" }, "9948": { op: "Vi", circle: "Andhra Pradesh" },
    // BSNL
    "9411": { op: "BSNL", circle: "UP West" }, "9412": { op: "BSNL", circle: "UP West" },
    "9413": { op: "BSNL", circle: "Rajasthan" }, "9418": { op: "BSNL", circle: "HP" },
    "9419": { op: "BSNL", circle: "J&K" }, "9422": { op: "BSNL", circle: "Maharashtra" },
    "9423": { op: "BSNL", circle: "Maharashtra" }, "9450": { op: "BSNL", circle: "UP East" },
    "9451": { op: "BSNL", circle: "UP East" }, "9452": { op: "BSNL", circle: "UP East" },
    "9453": { op: "BSNL", circle: "UP East" }, "9454": { op: "BSNL", circle: "UP East" },
    "9455": { op: "BSNL", circle: "UP East" },
};

// ── Plans database per operator (Real plans as of 2025-26)
export const OPERATOR_PLANS = {
    Airtel: [
        // Data Add-ons
        { id: 1, amount: 22, data: "1 GB", validity: "1 Day", calls: "—", sms: "—", type: "Data", popular: false, desc: "Data booster pack" },
        { id: 2, amount: 33, data: "2 GB", validity: "1 Day", calls: "—", sms: "—", type: "Data", popular: false, desc: "Emergency data add-on" },
        { id: 3, amount: 99, data: "Unlimited", validity: "2 Days", calls: "—", sms: "—", type: "Data", popular: false, desc: "Unlimited 5G/4G Data booster" },
        // All-in-1 Monthly & Budget
        { id: 4, amount: 199, data: "2 GB total", validity: "28 Days", calls: "Unlimited", sms: "100/D", type: "All-in-1", popular: false, desc: "Budget monthly plan" },
        { id: 5, amount: 299, data: "1.5 GB/Day", validity: "28 Days", calls: "Unlimited", sms: "100/D", type: "All-in-1", popular: true, desc: "Daily data monthly seller" },
        { id: 6, amount: 349, data: "2 GB/Day", validity: "28 Days", calls: "Unlimited", sms: "100/D", type: "5G", popular: false, desc: "Airtel 5G monthly pack" },
        { id: 7, amount: 379, data: "2 GB/Day", validity: "1 Month", calls: "Unlimited", sms: "100/D", type: "5G", popular: false, desc: "Calendar Month 5G validity" },
        { id: 8, amount: 409, data: "2.5 GB/Day", validity: "28 Days", calls: "Unlimited", sms: "100/D", type: "5G", popular: false, desc: "High daily 5G data pack" },
        { id: 9, amount: 449, data: "3 GB/Day", validity: "28 Days", calls: "Unlimited", sms: "100/D", type: "5G", popular: false, desc: "Max daily 5G data pack" },
        // Multi-Month & 5G Packs
        { id: 10, amount: 579, data: "1.5 GB/Day", validity: "56 Days", calls: "Unlimited", sms: "100/D", type: "All-in-1", popular: false, desc: "2-Month daily data plan" },
        { id: 11, amount: 649, data: "2 GB/Day", validity: "56 Days", calls: "Unlimited", sms: "100/D", type: "5G", popular: false, desc: "2-Month 5G unlimited pack" },
        { id: 12, amount: 859, data: "1.5 GB/Day", validity: "84 Days", calls: "Unlimited", sms: "100/D", type: "All-in-1", popular: true, desc: "Standard 84 Days bestseller" },
        { id: 13, amount: 979, data: "2 GB/Day", validity: "84 Days", calls: "Unlimited", sms: "100/D", type: "5G", popular: true, desc: "84 Days 5G unlimited bundle" },
        // Annual
        { id: 14, amount: 1999, data: "24 GB total", validity: "365 Days", calls: "Unlimited", sms: "3600 total", type: "Annual", popular: false, desc: "Value annual calling plan" },
        { id: 15, amount: 3599, data: "2 GB/Day", validity: "365 Days", calls: "Unlimited", sms: "100/D", type: "Annual", popular: true, desc: "Premium annual 5G unlimited pack" },
    ],

    Jio: [
        // Data Add-ons
        { id: 1, amount: 19, data: "1 GB", validity: "1 Day", calls: "—", sms: "—", type: "Data", popular: false, desc: "Emergency data add-on" },
        { id: 2, amount: 29, data: "2 GB", validity: "1 Day", calls: "—", sms: "—", type: "Data", popular: false, desc: "Standard high-speed data booster" },
        { id: 3, amount: 49, data: "Unlimited", validity: "1 Day", calls: "—", sms: "—", type: "Data", popular: false, desc: "True unlimited active plan upgrade" },
        // Monthly
        { id: 4, amount: 199, data: "1.5 GB/Day", validity: "18 Days", calls: "Unlimited", sms: "100/D", type: "All-in-1", popular: false, desc: "Short term budget plan" },
        { id: 5, amount: 249, data: "1 GB/Day", validity: "28 Days", calls: "Unlimited", sms: "100/D", type: "All-in-1", popular: false, desc: "Starter monthly plan" },
        { id: 6, amount: 299, data: "1.5 GB/Day", validity: "28 Days", calls: "Unlimited", sms: "100/D", type: "All-in-1", popular: true, desc: "Standard monthly bestseller" },
        { id: 7, amount: 349, data: "2 GB/Day", validity: "28 Days", calls: "Unlimited", sms: "100/D", type: "5G", popular: true, desc: "True 5G Unlimited monthly pack" },
        { id: 8, amount: 399, data: "2.5 GB/Day", validity: "28 Days", calls: "Unlimited", sms: "100/D", type: "5G", popular: false, desc: "High speed 5G monthly pack" },
        { id: 9, amount: 449, data: "3 GB/Day", validity: "28 Days", calls: "Unlimited", sms: "100/D", type: "5G", popular: false, desc: "Max daily 5G monthly pack" },
        // Multi-Month
        { id: 10, amount: 579, data: "1.5 GB/Day", validity: "56 Days", calls: "Unlimited", sms: "100/D", type: "All-in-1", popular: false, desc: "2-Month standard plan" },
        { id: 11, amount: 629, data: "2 GB/Day", validity: "56 Days", calls: "Unlimited", sms: "100/D", type: "5G", popular: false, desc: "2-Month 5G unlimited pack" },
        { id: 12, amount: 799, data: "1.5 GB/Day", validity: "84 Days", calls: "Unlimited", sms: "100/D", type: "All-in-1", popular: true, desc: "84 Days value calling pack" },
        { id: 13, amount: 859, data: "2 GB/Day", validity: "84 Days", calls: "Unlimited", sms: "100/D", type: "5G", popular: true, desc: "84 Days 5G unlimited bestseller" },
        { id: 14, amount: 899, data: "2 GB/Day + 20 GB", validity: "90 Days", calls: "Unlimited", sms: "100/D", type: "5G", popular: false, desc: "3-Month 5G bundle + bonus data" },
        { id: 15, amount: 999, data: "2 GB/Day", validity: "98 Days", calls: "Unlimited", sms: "100/D", type: "5G", popular: false, desc: "Hero 5G pack with 98 days validity" },
        // Annual
        { id: 16, amount: 1899, data: "24 GB total", validity: "365 Days", calls: "Unlimited", sms: "3600 total", type: "Annual", popular: false, desc: "Annual value plan" },
        { id: 17, amount: 3599, data: "2.5 GB/Day", validity: "365 Days", calls: "Unlimited", sms: "100/D", type: "Annual", popular: true, desc: "Premium annual 5G unlimited pack" },
    ],

    Vi: [
        // Data Add-ons
        { id: 1, amount: 22, data: "1 GB", validity: "1 Day", calls: "—", sms: "—", type: "Data", popular: false, desc: "Data add-on pack" },
        { id: 2, amount: 33, data: "2 GB", validity: "1 Day", calls: "—", sms: "—", type: "Data", popular: false, desc: "Emergency data booster" },
        // Monthly
        { id: 3, amount: 199, data: "2 GB total", validity: "28 Days", calls: "Unlimited", sms: "300 total", type: "All-in-1", popular: false, desc: "Minimal budget plan" },
        { id: 4, amount: 299, data: "1.5 GB/Day", validity: "28 Days", calls: "Unlimited", sms: "100/D", type: "All-in-1", popular: true, desc: "Bestseller monthly plan with Hero benefits" },
        { id: 5, amount: 349, data: "2 GB/Day", validity: "28 Days", calls: "Unlimited", sms: "100/D", type: "All-in-1", popular: false, desc: "Unlimited monthly Hero pack" },
        { id: 6, amount: 379, data: "2 GB/Day", validity: "1 Month", calls: "Unlimited", sms: "100/D", type: "All-in-1", popular: false, desc: "Calendar Month Hero pack" },
        { id: 7, amount: 449, data: "3 GB/Day", validity: "28 Days", calls: "Unlimited", sms: "100/D", type: "All-in-1", popular: false, desc: "Max daily data monthly pack" },
        // Multi-Month
        { id: 8, amount: 579, data: "1.5 GB/Day", validity: "56 Days", calls: "Unlimited", sms: "100/D", type: "All-in-1", popular: false, desc: "2-Month daily data pack" },
        { id: 9, amount: 649, data: "2 GB/Day", validity: "56 Days", calls: "Unlimited", sms: "100/D", type: "All-in-1", popular: false, desc: "2-Month Hero pack" },
        { id: 10, amount: 859, data: "1.5 GB/Day", validity: "84 Days", calls: "Unlimited", sms: "100/D", type: "All-in-1", popular: true, desc: "84 Days standard Hero pack" },
        { id: 11, amount: 979, data: "2 GB/Day", validity: "84 Days", calls: "Unlimited", sms: "100/D", type: "All-in-1", popular: false, desc: "84 Days premium Hero pack" },
        // Annual
        { id: 12, amount: 1999, data: "24 GB total", validity: "365 Days", calls: "Unlimited", sms: "3600 total", type: "Annual", popular: false, desc: "Annual value plan" },
        { id: 13, amount: 3499, data: "2 GB/Day", validity: "365 Days", calls: "Unlimited", sms: "100/D", type: "Annual", popular: true, desc: "Premium annual Hero pack" },
    ],

    BSNL: [
        // Short Term
        { id: 1, amount: 22, data: "1 GB", validity: "18 Days", calls: "Unlimited", sms: "100/D", type: "All-in-1", popular: false, desc: "Ultra budget starter" },
        { id: 2, amount: 25, data: "2 GB", validity: "2 Days", calls: "Unlimited", sms: "—", type: "Daily", popular: false, desc: "Weekend plan" },
        { id: 3, amount: 56, data: "1 GB/Day", validity: "7 Days", calls: "Unlimited", sms: "100/D", type: "Weekly", popular: false, desc: "Weekly plan — 7 GB" },
        { id: 4, amount: 94, data: "2 GB/Day", validity: "20 Days", calls: "Unlimited", sms: "100/D", type: "All-in-1", popular: false, desc: "20-day val plan" },
        // Monthly
        { id: 5, amount: 107, data: "2 GB/Day", validity: "22 Days", calls: "Unlimited", sms: "100/D", type: "All-in-1", popular: false, desc: "22-day plan" },
        { id: 6, amount: 118, data: "1 GB/Day", validity: "26 Days", calls: "Unlimited", sms: "100/D", type: "All-in-1", popular: false, desc: "26-day plan — 26 GB" },
        { id: 7, amount: 148, data: "2 GB/Day", validity: "26 Days", calls: "Unlimited", sms: "100/D", type: "All-in-1", popular: false, desc: "26 days — 52 GB" },
        { id: 8, amount: 197, data: "2 GB/Day", validity: "28 Days", calls: "Unlimited", sms: "100/D", type: "All-in-1", popular: true, desc: "Best BSNL — 56 GB + Disney+ Hotstar" },
        { id: 9, amount: 237, data: "3 GB/Day", validity: "28 Days", calls: "Unlimited", sms: "100/D", type: "All-in-1", popular: false, desc: "84 GB monthly" },
        { id: 10, amount: 247, data: "2 GB/Day", validity: "30 Days", calls: "Unlimited", sms: "100/D", type: "All-in-1", popular: false, desc: "30 days — 60 GB" },
        // 3-Month
        { id: 11, amount: 397, data: "3 GB/Day", validity: "80 Days", calls: "Unlimited", sms: "100/D", type: "All-in-1", popular: false, desc: "80 days — 240 GB" },
        { id: 12, amount: 485, data: "2 GB/Day", validity: "90 Days", calls: "Unlimited", sms: "100/D", type: "All-in-1", popular: false, desc: "Quarterly — 180 GB" },
        { id: 13, amount: 599, data: "2 GB/Day", validity: "120 Days", calls: "Unlimited", sms: "100/D", type: "All-in-1", popular: false, desc: "4 months — 240 GB" },
        // Long Term
        { id: 14, amount: 797, data: "3 GB/Day", validity: "160 Days", calls: "Unlimited", sms: "100/D", type: "All-in-1", popular: false, desc: "5 months — 480 GB" },
        { id: 15, amount: 1198, data: "3 GB/Day", validity: "240 Days", calls: "Unlimited", sms: "100/D", type: "All-in-1", popular: false, desc: "8 months plan" },
        // Annual
        { id: 16, amount: 1515, data: "2 GB/Day", validity: "365 Days", calls: "Unlimited", sms: "100/D", type: "Annual", popular: false, desc: "Annual — 730 GB" },
        { id: 17, amount: 2399, data: "3 GB/Day", validity: "365 Days", calls: "Unlimited", sms: "100/D", type: "Annual", popular: true, desc: "Annual best — 1095 GB + Disney+" },
    ],
};


// ── DTH Providers & Plans (Updated with Venus Opcodes)
export const DTH_PROVIDERS = {
    "Tata Play": {
        logo: "🔵",
        color: "#003087",
        opcode: "TSY",
        plans: [
            { id: 1, amount: 199, name: "Basic SD", channels: "210+", validity: "30 Days", type: "SD" },
            { id: 2, amount: 299, name: "Basic HD", channels: "220+", validity: "30 Days", type: "HD" },
            { id: 3, amount: 399, name: "Family HD", channels: "290+", validity: "30 Days", type: "HD" },
            { id: 4, amount: 499, name: "Super HD", channels: "350+", validity: "30 Days", type: "HD" },
            { id: 5, amount: 699, name: "Premium 4K", channels: "400+", validity: "30 Days", type: "4K" },
        ]
    },
    "Airtel Digital TV": {
        logo: "🔴",
        color: "#E40000",
        opcode: "ATD",
        plans: [
            { id: 1, amount: 249, name: "Base SD", channels: "200+", validity: "30 Days", type: "SD" },
            { id: 2, amount: 349, name: "HD Basic", channels: "250+", validity: "30 Days", type: "HD" },
            { id: 3, amount: 499, name: "HD Family", channels: "320+", validity: "30 Days", type: "HD" },
            { id: 4, amount: 599, name: "HD Premium", channels: "400+", validity: "30 Days", type: "HD" },
            { id: 5, amount: 799, name: "Elite 4K", channels: "450+", validity: "30 Days", type: "4K" },
        ]
    },
    "Dish TV": {
        logo: "🟠",
        color: "#FF6600",
        opcode: "DTV",
        plans: [
            { id: 1, amount: 153, name: "Silver SD", channels: "195+", validity: "30 Days", type: "SD" },
            { id: 2, amount: 249, name: "Gold SD", channels: "260+", validity: "30 Days", type: "SD" },
            { id: 3, amount: 349, name: "Diamond HD", channels: "310+", validity: "30 Days", type: "HD" },
            { id: 4, amount: 499, name: "Platinum HD", channels: "380+", validity: "30 Days", type: "HD" },
        ]
    },
    "Sun Direct": {
        logo: "🟡",
        color: "#FFA500",
        opcode: "STV",
        plans: [
            { id: 1, amount: 149, name: "Silver", channels: "125+", validity: "30 Days", type: "SD" },
            { id: 2, amount: 249, name: "Gold", channels: "205+", validity: "30 Days", type: "SD" },
            { id: 3, amount: 349, name: "Diamond HD", channels: "240+", validity: "30 Days", type: "HD" },
            { id: 4, amount: 499, name: "Platinum", channels: "300+", validity: "30 Days", type: "HD" },
        ]
    },
    "Videocon D2H": {
        logo: "🔷",
        color: "#0066CC",
        opcode: "VCD",
        plans: [
            { id: 1, amount: 125, name: "Lite SD", channels: "155+", validity: "30 Days", type: "SD" },
            { id: 2, amount: 249, name: "Smart HD", channels: "230+", validity: "30 Days", type: "HD" },
            { id: 3, amount: 399, name: "Super HD", channels: "290+", validity: "30 Days", type: "HD" },
            { id: 4, amount: 549, name: "Ultra HD", channels: "350+", validity: "30 Days", type: "HD" },
        ]
    },
    "Big TV": {
        logo: "📡",
        color: "#e11d48",
        opcode: "BTV",
        plans: []
    }
};

// ── BBPS Bill Categories & All India Billers
export const BILL_CATEGORIES = [
    {
        id: "electricity", label: "Electricity", icon: "⚡", color: "#f59e0b",
        billers: [
            { name: "Goa Electricity Department", opcode: "GOE" },
            { name: "UPPCL - URBAN (Uttar Pradesh)", opcode: "UBE" },
            { name: "UPPCL - RURAL (Uttar Pradesh)", opcode: "URE" },
            { name: "UPPCL - Smart Prepaid Recharge", opcode: "UPSR" },
            { name: "Dakshinanchal Vidyut Vitran Nigam (DVVNL)", opcode: "DVV" },
            { name: "Madhyanchal Vidyut Vitran Nigam (MVVNL)", opcode: "MVV" },
            { name: "Pashchimanchal Vidyut Vitran Nigam (PVVNL)", opcode: "PVE" },
            { name: "Purvanchal Vidyut Vitran Nigam (PUVVNL)", opcode: "PUV" },
            { name: "BSES Yamuna Power Limited (Delhi)", opcode: "BYE" },
            { name: "BSES Rajdhani Power Limited (Delhi)", opcode: "BRE" },
            { name: "Tata Power (Delhi) - DDL", opcode: "NDE" },
            { name: "Adani Electricity Mumbai Limited", opcode: "ADE" },
            { name: "Tata Power Mumbai", opcode: "TME" },
            { name: "MSEDC Limited (Maharashtra)", opcode: "MSE" },
            { name: "BEST Mumbai", opcode: "BME" },
            { name: "Torrent Power - Ahmedabad", opcode: "THE" },
            { name: "Torrent Power - Surat", opcode: "TSE" },
            { name: "Torrent Power - Bhiwandi", opcode: "TBE" },
            { name: "Torrent Power - Agra", opcode: "TAE" },
            { name: "Dakshin Gujarat Vij Company (DGVCL)", opcode: "DGE" },
            { name: "Madhya Gujarat Vij Company (MGVCL)", opcode: "MGE" },
            { name: "Paschim Gujarat Vij Company (PGVCL)", opcode: "PGE" },
            { name: "Uttar Gujarat Vij Company (UGVCL)", opcode: "UGE" },
            { name: "CESC (Calcutta Electric)", opcode: "CWE" },
            { name: "WBSEDCL (West Bengal)", opcode: "WBE" },
            { name: "PSPCL (Punjab State Power)", opcode: "PSE" },
            { name: "DHBVN (Dakshin Haryana)", opcode: "DHE" },
            { name: "UHBVN (Uttar Haryana)", opcode: "UHE" },
            { name: "KSEB (Kerala State Electricity)", opcode: "KSE" },
            { name: "Bangalore Electricity Supply (BESCOM)", opcode: "BBE" },
            { name: "Hubli Electricity Supply (HESCOM)", opcode: "HNE" },
            { name: "Mangalore Electricity Supply (MESCOM)", opcode: "MNE" },
            { name: "Gulbarga Electricity Supply (GESCOM)", opcode: "GEE" },
            { name: "Chamundeshwari Electricity (CESCOM)", opcode: "CNE" },
            { name: "TPADL (Ajmer Distribution)", opcode: "AJE" },
            { name: "JVVNL (Jaipur Vidyut)", opcode: "JIE" },
            { name: "JDVVNL (Jodhpur Vidyut)", opcode: "JDE" },
            { name: "AVVNL (Ajmer Vidyut)", opcode: "AVE" },
            { name: "JBVNL (Jharkhand Bijli)", opcode: "JBE" },
            { name: "NBPDCL (North Bihar)", opcode: "NBE" },
            { name: "SBPDCL (South Bihar)", opcode: "SBE" },
            { name: "Chhattisgarh State Electricity", opcode: "CCE" },
            { name: "MP Paschim Kshetra (Indore)", opcode: "MPE" },
            { name: "MP Madhya Kshetra (Bhopal)", opcode: "MUE" },
            { name: "MP Poorv Kshetra (Jabalpur)", opcode: "MKE" },
            { name: "APSPDCL (Andhra Pradesh Southern)", opcode: "ASE" },
            { name: "APEPDCL (Andhra Pradesh Eastern)", opcode: "APE" },
            { name: "TNEB (Tamil Nadu Electricity)", opcode: "TNE" },
            { name: "Uttarakhand Power (UPCL)", opcode: "UKE" },
            { name: "Himachal Pradesh (HPSEB)", opcode: "HPE" },
        ],
    },
    {
        id: "fastag", label: "FASTag", icon: "🚗", color: "#3b82f6",
        billers: [
            { name: "SBI FASTAG", opcode: "SBF" },
            { name: "PAYTM PAYMENTS BANK FASTAG", opcode: "PPF" },
            { name: "ICICI BANK FASTAG", opcode: "ICF" },
            { name: "HDFC BANK FASTAG", opcode: "HBF" },
            { name: "AXIS BANK FASTAG", opcode: "ABF" },
            { name: "KOTAK MAHINDRA BANK - FASTAG", opcode: "KMF" },
            { name: "IDFC FIRST BANK FASTAG", opcode: "IFF" },
            { name: "BANK OF BARODA FASTAG", opcode: "BBF" },
            { name: "AIRTEL FASTAG", opcode: "ATF" },
            { name: "FEDERAL BANK FASTAG", opcode: "FBF" },
            { name: "IndusInd Bank FASTag", opcode: "INF" },
            { name: "Indian Bank Fastag", opcode: "IDF" },
            { name: "Canara Bank Fastag", opcode: "CBF" },
            { name: "Bank of Maharashtra Fastag", opcode: "BMF" },
            { name: "Union Bank of India FASTag", opcode: "UIF" },
            { name: "Saraswat Bank - FASTag", opcode: "SWF" },
            { name: "South Indian Bank Fastag", opcode: "SIF" },
            { name: "UCO BANK FASTAG", opcode: "UBF" },
            { name: "Jammu & Kashmir Bank Fastag", opcode: "JKF" },
            { name: "Karnataka Bank Fastag", opcode: "KBF" },
            { name: "IDBI Bank Fastag", opcode: "IBF" },
            { name: "EQUITYAS FASTAG", opcode: "EQF" },
        ],
    },
    {
        id: "insurance", label: "Insurance", icon: "🛡️", color: "#10b981",
        billers: [
            { name: "LIC", opcode: "LIC" },
            { name: "HDFC Life Insurance", opcode: "HLI" },
            { name: "SBI Life Insurance", opcode: "SBI" },
            { name: "ICICI Prudential Life Insurance", opcode: "IPI" },
            { name: "TATA AIA Life Insurance", opcode: "TAI" },
            { name: "Star Union Dai-ichi Life Insurance", opcode: "SDI" },
            { name: "Religare Health Insurance (Care)", opcode: "RHI" },
            { name: "Reliance Nippon Life Insurance", opcode: "RNI" },
            { name: "Shriram Life Insurance", opcode: "SLI" },
            { name: "Pramerica Life Insurance", opcode: "PLI" },
            { name: "PNB MetLife Insurance", opcode: "PMI" },
            { name: "Max Life Insurance", opcode: "MLI" },
            { name: "IDBI Federal Life Insurance", opcode: "IFI" },
            { name: "Bajaj Allianz Life Insurance", opcode: "BAI" },
            { name: "Aditya Birla Sun Life Insurance", opcode: "ABI" },
            { name: "Aviva Life Insurance", opcode: "ALI" },
            { name: "Bharti AXA Life Insurance", opcode: "BXI" },
            { name: "Canara HSBC OBC Life Insurance", opcode: "CHI" },
            { name: "Exide Life Insurance", opcode: "ELI" },
            { name: "Edelweiss Tokio Life Insurance", opcode: "ETI" },
            { name: "Future Generali India Life Insurance", opcode: "FGI" },
            { name: "IndiaFirst Life Insurance", opcode: "FII" },
            { name: "Kotak Mahindra Life Insurance", opcode: "KMI" },
        ],
    },
    {
        id: "gas", label: "Piped Gas", icon: "🔥", color: "#ef4444",
        billers: [
            { name: "Indraprastha Gas (IPG)", opcode: "IPG" },
            { name: "Mahanagar Gas (MMG)", opcode: "MMG" },
            { name: "Gujarat Gas Limited (GJG)", opcode: "GJG" },
            { name: "Indane Gas (IGG)", opcode: "IGG" },
            { name: "Hindustan Petroleum (HPG)", opcode: "HPG" },
            { name: "Bharat Petroleum (BPG)", opcode: "BPG" },
            { name: "Adani Gas (AGG)", opcode: "AGG" },
            { name: "Gail Gas Limited (GLG)", opcode: "GLG" },
            { name: "Green Gas Limited (GRG)", opcode: "GRG" },
            { name: "Maharashtra Natural Gas (MNG)", opcode: "MNG" },
            { name: "Sabarmati Gas (SMG)", opcode: "SMG" },
            { name: "Vadodara Gas (VDG)", opcode: "VDG" },
            { name: "Aavantika Gas (AVG)", opcode: "AVG" },
            { name: "Bhagyanagar Gas (BHG)", opcode: "BHG" },
            { name: "Central U.P. Gas (CUG)", opcode: "CUG" },
            { name: "Haryana City Gas (HCG)", opcode: "HCG" },
            { name: "Assam Gas (ASG)", opcode: "ASG" },
            { name: "Tripura Natural Gas (TNG)", opcode: "TNG" },
            { name: "Siti Energy (SIG)", opcode: "SIG" },
            { name: "ACM Gas Limited (AGG)", opcode: "AGG" },
        ],
    },
    {
        id: "postpaid", label: "Postpaid / Mobile Bill", icon: "📱", color: "#8b5cf6",
        billers: [
            { name: "Airtel Mobile Bill (ATM)", opcode: "ATM" },
            { name: "Jio Postpaid Bill (JIB)", opcode: "JIB" },
            { name: "Vodafone Idea Bill (VFM)", opcode: "VFM" },
            { name: "BSNL Mobile Bill (BSM)", opcode: "BSM" },
            { name: "Aircel Postpaid Bill (ACB)", opcode: "ACB" },
            { name: "Tata Docomo Bill (DOM)", opcode: "DOM" },
            { name: "Reliance Mobile Bill (REM)", opcode: "REM" },
            { name: "MTNL Delhi Postpaid (MLD)", opcode: "MLD" },
            { name: "Idea Mobile Bill (IDM)", opcode: "IDM" },
        ],
    },
    {
        id: "landline", label: "Landline Bill", icon: "📞", color: "#06b6d4",
        billers: [
            { name: "Airtel Landline Bill (ARL)", opcode: "ARL" },
            { name: "BSNL Landline Bill (BSL)", opcode: "BSL" },
            { name: "MTNL Landline Delhi (MLD)", opcode: "MLD" },
            { name: "Tata Indicom Landline (TIL)", opcode: "TIL" },
            { name: "Idea Landline Bill (IDL)", opcode: "IDL" },
            { name: "Tikona Postpaid (TKN)", opcode: "TKN" },
        ],
    },
    {
        id: "data_card", label: "Data Card", icon: "📶", color: "#6366f1",
        billers: [
            { name: "Airtel Data Card", opcode: "ACD" },
            { name: "Jio Data Card", opcode: "JIO" },
            { name: "BSNL Data Card", opcode: "BNL" },
            { name: "Idea Data Card", opcode: "IDD" },
            { name: "Tata Photon Plus", opcode: "TPP" },
            { name: "Tata Photon Whiz", opcode: "TPW" },
            { name: "MTS MBlaze", opcode: "MBZ" },
            { name: "MTS MBrowse", opcode: "MBS" },
            { name: "Reliance Net Plus", opcode: "RNP" },
            { name: "Reliance Netconnect", opcode: "RNC" },
        ],
    },
];


// ── PAN API Endpoint (backend)
export const PAN_API = "/api/pan/apply";
export const RECHARGE_API = "/api/recharge";
export const BILL_PAY_API = "/api/bill-pay";
export const BILL_FETCH_API = "/api/bill-fetch";

