-- Migration V18: No-op. Enabling RLS on flyway_schema_history is not recommended
-- as it requires an ACCESS EXCLUSIVE lock that conflicts with Flyway's internal locks,
-- causing statement timeouts and preventing successful deployments.
