spring.application.name=aeps


# ===============================
# Server Config
# ===============================
server.port=8080

# ===============================
# Database Config (AWS RDS)
# ===============================
spring.datasource.url=jdbc:mysql://database-2.cd2eyywiufeo.ap-south-1.rds.amazonaws.com:3306/venus_db?useSSL=false&allowPublicKeyRetrieval=true&serverTimezone=Asia/Kolkata
spring.datasource.username=admin
spring.datasource.password=Ajay9102
spring.datasource.driver-class-name=com.mysql.cj.jdbc.Driver

# ===============================
# JPA / Hibernate Config
# ===============================
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.MySQLDialect
spring.jpa.properties.hibernate.format_sql=true

# ===============================
# Hikari Pool Config
# ===============================
spring.datasource.hikari.maximum-pool-size=10
spring.datasource.hikari.minimum-idle=5
spring.datasource.hikari.idle-timeout=30000
spring.datasource.hikari.connection-timeout=20000
spring.datasource.hikari.max-lifetime=1800000

# ===============================
# Levin AEPS Config
# ===============================
levin.aeps.base-url=https://api.levinfintech.com/api/levin/v9
levin.aeps.user-id=276
levin.aeps.api-token=uJI6kLgdxPUNa7gSGyC4D52o9AheV3jTFSUeHq8Jml0JhCK8EcqBIQfd96yafrT1
levin.aeps.encryption-key=EmloAl9K53jmN1J2etNQn06xDiZQBiXg

# ===============================
# Logging
# ===============================
logging.level.org.springframework.web=DEBUG
logging.level.org.hibernate.SQL=DEBUG
logging.level.org.springframework.web.client.RestTemplate=DEBUG